version: "3"
services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_compuze
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=compuzedb
    volumes:
      - ./compuzedb:/var/lib/mysql
