export const FAKE_USERS = [
    {
        username: 'seller1',
        password: '123123oO',
        email: 'compuze@compuze.com',
        phone: 71717171,
    },
    {
        username: 'seller2',
        password: '123123oO',
        email: 'seller@seller.com',
        phone: 70707070,
    },
];

export const FAKE_ITEMS = [
    {
        type: 'SSD',
        brand: 'Kingston',
        model: 'A400',
        description: 'Blabla SSD',
        location: 'Beirut',
        imageSrc: 'default',
        price: 20,
        userId: 1,
    },
    {
        type: 'SSD',
        brand: 'Transcend',
        model: 'QX2',
        description: 'Blabla SSD',
        location: 'Byblos',
        imageSrc: 'default',
        price: 45,
        userId: 1,
    },
    {
        type: 'CPU',
        brand: 'Intel',
        model: 'i5-2500K',
        description: 'Blabla CPU',
        location: 'Beirut',
        imageSrc: 'default',
        price: 50,
        userId: 1,
    },
    {
        type: 'CPU',
        brand: 'AMD',
        model: 'Ryzen 3400',
        description: 'Blabla CPU',
        location: 'Tyr',
        imageSrc: 'default',
        price: 75,
        userId: 1,
    },
    {
        type: 'RAM',
        brand: 'Corsair',
        model: 'Vega X2 16GB DDR5',
        description: 'Blabla RAM',
        location: 'Byblos',
        imageSrc: 'default',
        price: 175,
        userId: 1,
    },
    {
        type: 'Case',
        brand: 'Coolermaster',
        model: 'TowerBlast 2K',
        description: 'Blabla Case',
        location: 'Byblos',
        imageSrc: 'default',
        price: 175,
        userId: 1,
    },
    {
        type: 'GPU',
        brand: 'NVIDIA',
        model: 'GTX 760',
        description: 'Blabla GPU',
        location: 'Beirut',
        imageSrc: 'default',
        price: 75,
        userId: 1,
    },
    {
        type: 'GPU',
        brand: 'NVIDIA',
        model: 'RTX 4090',
        description: 'Blabla GPU',
        location: 'Beirut',
        imageSrc: 'default',
        price: 975,
        userId: 1,
    },
    {
        type: 'GPU',
        brand: 'AMD',
        model: 'RX 7999',
        description: 'Blabla GPU',
        location: 'Byblos',
        imageSrc: 'default',
        price: 375,
        userId: 1,
    },
    {
        type: 'Cooling',
        brand: 'Thermaltake',
        model: 'CoolFlo 30x',
        description: 'Blabla Cooling',
        location: 'Byblos',
        imageSrc: 'default',
        price: 245,
        userId: 1,
    },
    {
        type: 'Cooling',
        brand: 'Coolermaster',
        model: 'Liquid X33',
        description: 'Blabla Cooling',
        location: 'Byblos',
        imageSrc: 'default',
        price: 105,
        userId: 1,
    },
    {
        type: 'Motherboard',
        brand: 'Intel',
        model: 'DB67GB',
        description: 'Blabla MB',
        location: 'Byblos',
        imageSrc: 'default',
        price: 35,
        userId: 1,
    },
    {
        type: 'Motherboard',
        brand: 'Asus',
        model: 'X99 Pro',
        description: 'Blabla MB',
        location: 'Beirut',
        imageSrc: 'default',
        price: 99,
        userId: 1,
    },
    {
        type: 'PSU',
        brand: 'Corsair',
        model: 'VF 700W',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 85,
        userId: 2,
    },
    {
        type: 'PSU',
        brand: 'Thermaltake',
        model: 'Smart SE 630W',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 55,
        userId: 2,
    },
    {
        type: 'RAM',
        brand: 'Kingston',
        model: '8 GB DDR4 KVR1600',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 30,
        userId: 2,
    },
    {
        type: 'HDD',
        brand: 'Seagate',
        model: 'Ironwolf 2TB',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 35,
        userId: 2,
    },
    {
        type: 'HDD',
        brand: 'WD',
        model: 'Purple Edition 8TB',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 130,
        userId: 2,
    },
    {
        type: 'Case',
        brand: 'Thermaltake',
        model: 'Battlemaster G5',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 100,
        userId: 2,
    },
    {
        type: 'CPU',
        brand: 'Intel',
        model: 'I7-7700K',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 200,
        userId: 2,
    },
    {
        type: 'RAM',
        brand: 'Corsair',
        model: 'Vengence 32GB DDR5 UBX3',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 100,
        userId: 2,
    },
    {
        type: 'SSD',
        brand: 'Samsung',
        model: 'Evo 950 2TB',
        description: 'Blabla',
        location: 'Beirut',
        imageSrc: 'default',
        price: 90,
        userId: 2,
    },
];
